import { Wifi, Phone, Mail } from "lucide-react";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NotebookPen } from "lucide-react";
import { Search } from "lucide-react";
import { NotebookPenIcon } from "lucide-react";
import { MapPinnedIcon } from "lucide-react";
import { Clock8 } from "lucide-react";
import { MailIcon } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex flex-row w-full justify-between px-16 py-4 items-center border-b-2 border-solid border-gray-700">
          <div className="flex flex-row gap-4 items-center">
            <div className="bg-blue-600 text-white w-10 h-10 flex justify-center items-center rounded-lg">
              <Wifi className="text-[45px]" />
            </div>

            <div className="flex flex-col">
              <div className="text-2xl">
                <h1>
                  <b>FeedbackNet</b>
                </h1>
              </div>
              <div className="text-gray-600 font-medium">
                <p>Portal PQR/S</p>
              </div>
            </div>
          </div>
          <div className="flex flex-row items-center gap-10">
            <LayoutItem
              Icon={<Phone className="text-gray-600" />}
              label1="01 8000 123 456"
            />

            <LayoutItem
              Icon={<MailIcon className="text-gray-600" />}
              label1="soporte@feedbacknet.co"
            />
          </div>
        </header>

        <main> {children} </main>

        <footer className="bg-blue-950 w-full flex flex-col items-center">
          <div className="flex flex-row gap-18 justify-center items-start border-b-1 border-solid border-gray-700 py-10">
            <section className="w-lg ">
              <div className="flex flex-row items-center gap-3 py-2">
                <div className="bg-blue-600 text-white w-10 h-10 flex justify-center items-center rounded-lg ">
                  <Wifi className="text-[36px] " />
                </div>
                <h1 className="text-white font-bold text-lg">FeedbackNet</h1>{" "}
              </div>
              <p className="text-white py-3">
                Plataforma especializada en gestion de PQR/S para proveedores de
                servicios de internet en Colombia. Cumplimos con la Resolucion
                CRC 6242 de 2021.
              </p>
              <p className="text-emerald-300">Certifico de CRC 6242 de 2021</p>
            </section>

            <section className="flex flex-col justify-center ">
              <h1 className="text-white font-bold text-lg pb-3">Contacto</h1>
              <div className="flex flex-col  gap-3">
                <LayoutItem
                  Icon={<Phone className="text-white" />}
                  label="01 8000 123 456"
                />

                <LayoutItem
                  Icon={<Mail className="text-white" />}
                  label="soporte@feedbacknet.co"
                />

                <LayoutItem
                  Icon={<MapPinnedIcon className="text-white" />}
                  label="Bogota, Colombia"
                />

                <LayoutItem
                  Icon={<Clock8 className="text-white" />}
                  label="Lun - Vie: 8:00 AM - 6:00 PM"
                />
              </div>
            </section>

            <section className="flex justify-end ">
              <div>
                <h1 className="text-white font-bold text-lg  pb-3">Legal</h1>
                <p className="text-white pb-3">Terminos y Condiciones</p>
                <p className="text-white pb-3">Politica de Privacidad</p>
                <p className="text-white pb-3">Tratamiento de Datos</p>
                <p className="text-white pb-3">Resolucion CRC 6242</p>
              </div>
            </section>
          </div>
          <section className="flex flex-col text-gray-400 justify-center items-center py-9">
            <p>© 2024 FeedbackNet. Todos los derechos reservados. </p>
            <p>
              Sistema certificado para cumplimiento normativo de
              telecomunicaciones en Colombia
            </p>
          </section>
        </footer>
      </body>
    </html>
  );
}

function LayoutItem({ Icon, label, label1 }) {
  return (
    <div className="flex flex-row gap-1.5">
      {Icon}
      <p className="text-white">{label}</p>
      <p className="text-gray-600 font-bold text-[18px]">{label1}</p>
    </div>
  );
}
